"""empty message

Revision ID: a70dad8772f0
Revises: c6d0e5918238
Create Date: 2021-03-31 16:05:39.287987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a70dad8772f0'
down_revision = 'c6d0e5918238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('character', sa.Integer(), nullable=True))
    op.drop_constraint('character_ibfk_1', 'character', type_='foreignkey')
    op.create_foreign_key(None, 'character', 'favorite', ['character'], ['id'])
    op.drop_column('character', 'character_id')
    op.add_column('planet', sa.Column('planet', sa.Integer(), nullable=True))
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.create_foreign_key(None, 'planet', 'favorite', ['planet'], ['id'])
    op.drop_column('planet', 'planet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'planet', type_='foreignkey')
    op.create_foreign_key('planet_ibfk_1', 'planet', 'favorite', ['planet_id'], ['id'])
    op.drop_column('planet', 'planet')
    op.add_column('character', sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.create_foreign_key('character_ibfk_1', 'character', 'favorite', ['character_id'], ['id'])
    op.drop_column('character', 'character')
    # ### end Alembic commands ###
